apiVersion: v1
kind: Service
metadata:
  name: default-subdomain
spec:
  selector:
    name: kubernetes-example
  clusterIP: None
  ports:
  - port: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: kubernetes-example-webapi
  labels:
    name: kubernetes-example
spec:
  hostname: kubernetes-example-webapi
  subdomain: default-subdomain
  containers:
  - image: sheyenrath/kubernetes-example
    env:
    - name: TEST_ENV_VAR1
      value: "Value 1"
    name: kubernetes-example-webapi