apiVersion: v1
kind: Service
metadata:
  name: kubernetes-example-subdomain
spec:
  selector:
    name: kubernetes-example
  ports:
  - port: 80
  type: LoadBalancer
---
apiVersion: v1
kind: Pod
metadata:
  name: kubernetes-example-webapi
  labels:
    name: kubernetes-example
spec:
  hostname: kubernetes-example-webapi
  subdomain: kubernetes-example-subdomain
  containers:
  - image: sheyenrath/kubernetes-example
    env:
    - name: TEST_ENV_VAR1
      value: "Value 1"
    name: kubernetes-example-webapi
---
apiVersion: v1
kind: Pod
metadata:
  name: kubernetes-example-redis
  labels:
    name: kubernetes-example
spec:
  hostname: kubernetes-example-redis
  subdomain: kubernetes-example-subdomain
  containers:
  - image: redis
    name: kubernetes-example-redis